dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  http: ^0.13.6
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.11
  image_picker: ^0.8.8
  video_player: ^2.8.0
  flutter_chat_ui: ^1.6.0
  syncfusion_flutter_gauges: ^23.1.44
  charts_flutter: ^0.12.0
